parameters:
    pfrembot_rest_proxy.excluded_directories: [Test, Tests]

services:

    pfrembot_rest_proxy.php_parser.printer:
        public: false
        class: PhpParser\PrettyPrinter\Standard

    # Symfony services
    pfrembot_rest_proxy.symfony.filesystem:
        public: false
        class: Symfony\Component\Filesystem\Filesystem

    pfrembot_rest_proxy.symfony.finder:
        public: false
        class: Symfony\Component\Finder\Finder
        calls:
            - [files, []]
            - [in, ['%kernel.root_dir%/../src']]
            - [name, ['*.php']]
            - [exclude, ['%pfrembot_rest_proxy.excluded_directories%']]


    # rest proxy builder services
    pfrembot_rest_proxy.builder.proxy_builder:
        public: false
        class: Pfrembot\RestProxyBundle\Builder\ProxyBuilder
        arguments:
            - '@annotation_reader'

    ## proxy cache services
    pfrembot_rest_proxy.proxy_cache:
        public: false
        class: Pfrembot\RestProxyBundle\Cache\ProxyCache
        arguments:
            - '@pfrembot_rest_proxy.php_parser.printer'
            - '@pfrembot_rest_proxy.symfony.filesystem'
            - '%kernel.cache_dir%'

    pfrembot_rest_proxy.cache_warmer:
        public: false
        class: Pfrembot\RestProxyBundle\Cache\CacheWarmer
        arguments:
            - '@pfrembot_rest_proxy.symfony.finder'
            - '@pfrembot_rest_proxy.builder.proxy_builder'
            - '@pfrembot_rest_proxy.proxy_cache'
        tags:
            - { name: kernel.cache_warmer }

    ## proxy serializer subscriber
    pfrembot_rest_proxy.serializer.subscriber:
        class: Pfrembot\RestProxyBundle\Subscriber\SerializerSubscriber
        arguments:
            - '@annotation_reader'
            - '@service_container'
        tags:
            - { name: jms_serializer.event_subscriber }
